import { serve } from "inngest/next";
import { inngest } from "@/services/inngest/client";
import {
  processWhatsappMessage,
  followUpCron,
  processFollowUpJob,
  bufferMonitorWorker,
  weeklyContentReminder,
  subscriptionExpiryWorker,
  manualContentGenerate,
  processContentJob,
  processReviewCampaign,
  reviewAutopollCron,
  processReviewAutopollJob,
  publishScheduledPostsCron,
  processPublishPostJob,
  publishScheduledMediaCron,
  processScheduledMediaPublishJob,
  reviewSyncWorker,
  processReviewSyncJob,
  criticalAlertWorker,
  reviewReplyDraftedWorker,
  scheduleLeadFollowUpsJob,
  dispatchWhatsappFollowUpJob,
  processDemoBooking,
  generateAuditJob,
  cleanupStalePendingAudits,
  salesNurtureRequested,
  salesNurtureConsented,
  salesAgentReply,
  bookingAgentReply,
  reportAgentReply,
  reportCardDeliver,
  gbpNightlySyncScheduler,
  gbpSyncWorker,
  cleanupAbandonedSignups
} from "@/services/inngest/functions";

export const { GET, POST, PUT } = serve({
  client: inngest,
  functions: [
    processWhatsappMessage,
    followUpCron,
    processFollowUpJob,
    bufferMonitorWorker,
    weeklyContentReminder,
    subscriptionExpiryWorker,
    manualContentGenerate,
    processContentJob,
    processReviewCampaign,
    reviewAutopollCron,
    processReviewAutopollJob,
    publishScheduledPostsCron,
    processPublishPostJob,
    publishScheduledMediaCron,
    processScheduledMediaPublishJob,
    reviewSyncWorker,
    processReviewSyncJob,
    criticalAlertWorker,
    reviewReplyDraftedWorker,
    scheduleLeadFollowUpsJob,
    dispatchWhatsappFollowUpJob,
    processDemoBooking,
    generateAuditJob,
    cleanupStalePendingAudits,
    salesNurtureRequested,
    salesNurtureConsented,
    salesAgentReply,
    bookingAgentReply,
    reportAgentReply,
    reportCardDeliver,
    gbpNightlySyncScheduler,
    gbpSyncWorker,
    cleanupAbandonedSignups,
  ],
});
